### ISSUE TITLE
Recommendation: Add a Hide/Show Code Button

### ISSUE THREAD

**Issue by FeralBytes** [jayaarrgh/BookOfShaders-Godot#2]
I added a button to your implementation that I could click that allowed me to hide or show the text area so that I could better analyze the entire screen area.

```gdscript
func _on_HideShowCode_pressed():
    get_node("TextEdit").visible = (get_node("TextEdit").visible < true)
```

**Comment by jayaarrgh** [comment]
The "Edit Code" button already functions as a visibility toggle.
https://github.com/jayaarrgh/BookOfShaders-Godot/blob/1479f210daee51f79bc92f1a8f13ea071419f9f4/BookOfShaders.gd#L58
