### ISSUE TITLE
Remove 3d preview in web version

### ISSUE THREAD

**Issue by tavurth** [jayaarrgh/BookOfShaders-Godot#7]
Due to this bug in web versions of Godot https://github.com/godotengine/godot/issues/56670

This causes the whole computer to lockup for 30 seconds while 3D shaders are compiled.

As a reference tool this is not so user friendly, I would suggest that the 3D version is only used for downloaded instances of the software.

**Comment by jayaarrgh** [comment]
Thank you for pointing this out!
I had not noticed this, but I was getting a long lockup when switching to 3d mode too.

I believe I can switch to gles2 without issue.
So I can do that for just the html5 export.

You can checkout https://jayaarrgh.itch.io/book-of-shaders-godot and let me know if its resolved for you.

**Comment by tavurth** [comment]
Hi, thank you for the quick fix! Working now :)
